blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
	url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
	url(r'^category/(?P<pk>[0-9])/$', views.CategoryView.as_view(), name='category'),
	url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
]

comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
	url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),

]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible

import markdown
from django.utils.html import strip_tags

# 分类
class Category(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

# 标签
class Tag(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

class Post(models.Model):
	title = models.CharField(max_length=70)
	# 文章标题

	body = models.TextField()
	# 文章正文

	created_time = models.DateTimeField()    # 创建时间
	modified_time = models.DateTimeField()   # 最后修改时间
	# 文章创建时间和最后修改时间

	excerpt = models.CharField(max_length=200, blank=True)
	# 文章摘要， 指定CharField的blank=True参数值后就可以允许空值，因为默认为必须存入数据

	category = models.ForeignKey(Category)
	# 这文章对应的数据库表和分类、标签对应的数据表关联

	tags = models.ManyToManyField(Tag, blank=True)   # 多对多
	author = models.ForeignKey(User)                 # 一对多 

	def save(self, *args, **kwargs):
		# 如果没有填写摘要
		if not self.excerpt:
			# 首先实例化一个 Markdown 类，用于渲染 body 的文本
			md = markdown.Markdown(extensions=[
				'markdown.extensions.extra',
				'markdown.extensions.codehilite',
				])
			# 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
			self.excerpt = strip_tags(md.convert(self.body))[:100]

		# 调用父类的 save 方法将数据保存到数据库中
		super(Post, self).save(*args, **kwargs)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:detail', kwargs={'pk': self.pk})


	class Meta:
		ordering = ['-created_time']


	# 新增 views 字段记录阅读量
	views = models.PositiveIntegerField(default=0)

	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible


# python_2_unicode_compatible 装饰器用于兼容Python2
# @python_2_unicode_compatible
class Comment(models.Model):
	name = models.CharField(max_length=100)
	email = models.EmailField(max_length=255)
	url = models.URLField(blank=True)
	text = models.TextField()
	created_time = models.DateTimeField(auto_now_add=True)

	post = models.ForeignKey('blog.Post')

	def __str__(self):
		return self.text[:20]

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post, Category, Tag
import markdown
from comments.forms import CommentForm

from django.views.generic import ListView, DetailView

from django.utils.text import slugify
from markdown.extensions.toc import TocExtension


class IndexView(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'
	# 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
	paginate_by = 5

# def index(request):
# 	post_list = Post.objects.all().order_by('-created_time')
# 	return render(request, 'blog/index.html', context={"post_list": post_list})

	def get_context_data(self, **kwargs):
		"""
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """
        # 首先获得父类生成的传递给模板的字典。
		context = super().get_context_data(**kwargs)

		# 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
		paginator = context.get('paginator')
		page = context.get('page_obj')
		is_paginated = context.get('is_paginated')

		# 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
		pagination_data = self.pagination_data(paginator, page, is_paginated)

		# 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
		context.update(pagination_data)

		# 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
		return context

	def pagination_data(self, paginator, page, is_paginated):
		if not is_paginated:
			# 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
			return {}

		# 当前页左边连续的页码号，初始值为空
		left = []

		# 当前页右边连续的页码号，初始值为空
		right = []

		# 标示第 1 页页码后是否需要显示省略号
		left_has_more = False

		# 标示最后一页页码前是否需要显示省略号
		right_has_more = False

		# 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
		first = False

		# 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
		last = False

		# 获得用户当前请求的页码号
		page_number = page.number

		# 获得分页后的总页数
		total_pages = paginator.num_pages

		# 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
		page_range = paginator.page_range

		if page_number == 1:
			# 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
			right = page_range[page_number:page_number + 2]

			# 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
			if right[-1] < total_pages -1:
				right_has_more = True

			# 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
			if right[-1] < total_pages:
				last = True

		elif page_number == total_pages:
			# 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number -1]

			# 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
			if left[0] > 2:
				left_has_more = True

			# 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
			if left[0] > 1:
				first = True
		else:
			# 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
			left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number -1]
			right = page_range[page_number:page_number + 2]

			# 是否需要显示最后一页和最后一页前的省略号
			if right[-1] < total_pages - 1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True

			# 是否需要显示第 1 页和第 1 页后的省略号
			if left[0] > 2:
				left_has_more = True
			if left[0] > 1:
				first = True

		data = {
		'left': left,
		'right': right,
		'left_has_more': left_has_more,
		'right_has_more': right_has_more,
		'first': first,
		'last': last
		}

		return data


class PostDetailView(DetailView):
	model = Post
	template_name = 'blog/detail.html'
	context_object_name = 'post'

	def get(self, request, *args, **kwargs):
		# 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
		response = super(PostDetailView, self).get(request, *args, **kwargs)

		# 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
		self.object.increase_views()

		# 视图必须返回一个 HttpResponse 对象
		return response

	def get_object(self, queryset=None):
		# 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
		post = super(PostDetailView, self).get_object(queryset=None)
		md = markdown.Markdown(extensions=[
			'markdown.extensions.extra',
			'markdown.extensions.codehilite',
			TocExtension(slugify=slugify),
			# 'markdown.extensions.toc',
			])
		post.body = md.convert(post.body)
		post.toc = md.toc

		# post.body = markdown.markdown(post.body,
		# 								extensions=[
		# 								'markdown.extensions.extra',
		# 								'markdown.extensions.codehilite',
		# 								'markdown.extensions.toc',
		# 								])
		return post

	def get_context_data(self, **kwargs):
		# 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
        # 还要把评论表单、post 下的评论列表传递给模板。
		context = super(PostDetailView, self).get_context_data(**kwargs)
		form = CommentForm()
		comment_list = self.object.comment_set.all()
		context.update({
			'form': form,
			'comment_list': comment_list
			})

		return context


# def detail(request, pk):
# 	post = get_object_or_404(Post, pk=pk)

# 	# 阅读量
# 	post.increase_views()

# 	post.body = markdown.markdown(post.body,
# 									extensions=[
# 									'markdown.extensions.extra',
# 									'markdown.extensions.codehilite',
# 									'markdown.extensions.toc'
# 									])

# 	form = CommentForm()

# 	# 获取这篇 post 下的全部评论
# 	comment_list = post.comment_set.all()
	
# 	# 将文章、表单、以及文章下的评论列表作为模板变量传给 detail.html 模板，以便渲染相应数据。
# 	context = {'post': post,
# 				'form': form,
# 				'comment_list': comment_list
# 				}
# 	return render(request, 'blog/detail.html', context=context)


class ArchivesView(IndexView):

# class ArchivesView(ListView):
# 	model = Post
# 	template_name = 'blog/index.html'
# 	context_object_name = 'post_list'

	def get_queryset(self):
		year = self.kwargs.get('year')
		month = self.kwargs.get('month')
		return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
																created_time__month=month
																)


# def archives(request, year, month):
# 	post_list = Post.objects.filter(created_time__year=year,
# 									created_time__month=month,
# 									).order_by('-created_time')
# 	return render(request, 'blog/index.html', context={'post_list': post_list})


class CategoryView(IndexView):

# class CategoryView(ListView):
# 	model = Post
# 	template_name = 'blog/index.html'
# 	context_object_name = 'post_list'

	def get_queryset(self):
		cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
		return super(CategoryView, self).get_queryset().filter(category=cate)


# def category(request, pk):
# 	cate = get_object_or_404(Category, pk=pk)
# 	post_list = Post.objects.filter(category=cate).order_by('-created_time')
# 	return render(request, 'blog/index.html', context={'post_list': post_list})


class TagView(ListView):
	model = Post
	template_name = 'blog/index.html'
	context_object_name = 'post_list'

	def get_queryset(self):
		tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
		return super(TagView, self).get_queryset().filter(tags=tag)

templates/blog/detail.html
{% extends 'base.html' %}



            <main class="col-md-8">
            {% block main %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ post.body|safe }}
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_label }}">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="{{ form.text.id_for_label }}">评论：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 {{ post.comment_set.count }} 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date" >{{ comment.created_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                            暂无评论！
                            {% endfor %}
                        </ul>
                    </div>
                </section>
            {% endblock main %}
            {% block toc %}
            </main>
            
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    {{ post.toc|safe }}
                </div>
            {% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}

            
                {% block main %}
                {% for post in post_list %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">

                        <p>{{ post.excerpt }}</p>
                        <!-- <p>{{ post.body|truncatechars:100 }}</p> -->
                        
                        <div class="read-more cl-effect-14">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty %}
                <div class="no-post">暂时还没有发布的文章！</div>
                {% endfor %}

                
                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
<!-- 
                {% if is_paginated %}
                <div class="pagination-simple">
                    {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                    {% endif %}
                    <span class="current">第 {{ page_obj.number }} 页/共 {{ paginator.num_pages }} 页</span>
                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                    {% endif %}
                </div>
                {% endif %}
 -->



                {% if is_paginated %}
                <div class="pagination">
                    {% if first %}
                        <a href="?page=1">1</a>
                    {% endif %}
                    {% if left %}
                        {% if left_has_more %}
                            <span>...</span>
                        {% endif %}
                        {% for i in left %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endfor %}
                    {% endif %}
                    <a class="current-page" href="?page={{ page_obj.number }}" style="color: ">{{ page_obj.number }}</a>
                    {% if right %}
                        {% for i in right %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endfor %}
                        {% if right_has_more %}
                            <span>...</span>
                        {% endif %}
                    {% endif %}
                    {% if last %}
                        <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                    {% endif %}
                </div>
                {% endif %}



 <!--                <div class="pagination">
                    <ul>
                        <li><a href="">1</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">4</a></li>
                        <li><a href="">5</a></li>
                        <li class="current"><a href="">6</a></li>
                        <li><a href="">7</a></li>
                        <li><a href="">8</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">11</a></li>
                    </ul>
                </div> -->

                
            {% endblock main %}
            